# -*- coding: utf-8 -*-
"""String2Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1itA-la6Di_BKPLy1P7YIqSzLV8P7pSOe
"""

string = input()        #문자열로 입력 받음

cut = 7     #한 행에 출력할 데이터 수 설정

for i in range(0, len(string), 2):
    print("0x" + string[i:i+2], end = ' ')
    cut -= 1
    if(cut == 0):
        cut = 7
        print()

